// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolApp.Infrastructure.DatabaseContext;

#nullable disable

namespace SchoolApp.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContextSchool))]
    [Migration("20220128134103_DBSchemaV1")]
    partial class DBSchemaV1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Course", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("coursename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("professorid")
                        .HasColumnType("int");

                    b.Property<int>("studentid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedby")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("professorid");

                    b.HasIndex("studentid");

                    b.ToTable("courses");

                    b.HasData(
                        new
                        {
                            id = 1,
                            coursename = "Course 1",
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 531, DateTimeKind.Local).AddTicks(1962),
                            createdby = "Seed Data",
                            professorid = 1,
                            studentid = 1,
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 531, DateTimeKind.Local).AddTicks(1977),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 2,
                            coursename = "Course 2",
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 531, DateTimeKind.Local).AddTicks(1982),
                            createdby = "Seed Data",
                            professorid = 2,
                            studentid = 2,
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 531, DateTimeKind.Local).AddTicks(1984),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 3,
                            coursename = "Course 3",
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 531, DateTimeKind.Local).AddTicks(1986),
                            createdby = "Seed Data",
                            professorid = 3,
                            studentid = 3,
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 531, DateTimeKind.Local).AddTicks(1988),
                            updatedby = "Seed Data"
                        });
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Level", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime?>("createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("levelname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedby")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("levels");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(5406),
                            createdby = "Seed Data",
                            levelname = "Level 1",
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(5453),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 2,
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(5457),
                            createdby = "Seed Data",
                            levelname = "Level 2",
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(5459),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 3,
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(5462),
                            createdby = "Seed Data",
                            levelname = "Level 3",
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(5463),
                            updatedby = "Seed Data"
                        });
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("birthdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedby")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("persons");

                    b.HasData(
                        new
                        {
                            id = 1,
                            birthdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(5790),
                            createdby = "Seed Data",
                            firstname = "Marouane",
                            lastname = "EL MABROUK",
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(5795),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 2,
                            birthdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(5799),
                            createdby = "Seed Data",
                            firstname = "Smith",
                            lastname = "JOHN",
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(5801),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 3,
                            birthdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(5804),
                            createdby = "Seed Data",
                            firstname = "William",
                            lastname = "MILLER",
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(5805),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 4,
                            birthdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(5808),
                            createdby = "Seed Data",
                            firstname = "Prof",
                            lastname = "EL MABROUK",
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(5810),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 5,
                            birthdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(5812),
                            createdby = "Seed Data",
                            firstname = "Prof",
                            lastname = "JOHN",
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(5814),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 6,
                            birthdate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(5818),
                            createdby = "Seed Data",
                            firstname = "Prof",
                            lastname = "MILLER",
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(5820),
                            updatedby = "Seed Data"
                        });
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Professor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime?>("createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("personid")
                        .HasColumnType("int");

                    b.Property<string>("profcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedby")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("personid");

                    b.ToTable("professors");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(6962),
                            createdby = "Seed Data",
                            personid = 4,
                            profcode = "CODE_1",
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(6972),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 2,
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(6977),
                            createdby = "Seed Data",
                            personid = 5,
                            profcode = "CODE_2",
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(6979),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 3,
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(6981),
                            createdby = "Seed Data",
                            personid = 6,
                            profcode = "CODE_3",
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(6983),
                            updatedby = "Seed Data"
                        });
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime?>("createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedby")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(7266),
                            createdby = "Seed Data",
                            description = "Super Administrator Description",
                            role = 1,
                            title = "Super Administrator",
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(7270),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 2,
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(7277),
                            createdby = "Seed Data",
                            description = "Administrator Description",
                            role = 2,
                            title = "Administrator",
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(7279),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 3,
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(7281),
                            createdby = "Seed Data",
                            description = "User Description",
                            role = 3,
                            title = "User",
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(7283),
                            updatedby = "Seed Data"
                        });
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime?>("createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("levelid")
                        .HasColumnType("int");

                    b.Property<int>("personid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedby")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("levelid");

                    b.HasIndex("personid");

                    b.ToTable("students");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(9139),
                            createdby = "Seed Data",
                            levelid = 1,
                            personid = 1,
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(9149),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 2,
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(9154),
                            createdby = "Seed Data",
                            levelid = 2,
                            personid = 2,
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(9155),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 3,
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(9158),
                            createdby = "Seed Data",
                            levelid = 3,
                            personid = 3,
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 530, DateTimeKind.Local).AddTicks(9160),
                            updatedby = "Seed Data"
                        });
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime?>("createdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("personid")
                        .HasColumnType("int");

                    b.Property<int>("roleid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("updatedby")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("personid");

                    b.HasIndex("roleid");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 531, DateTimeKind.Local).AddTicks(4441),
                            createdby = "Seed Data",
                            email = "user1@mail.com",
                            password = "ba3253876aed6bc22d4a6ff53d8406c6ad864195ed144ab5c87621b6c233b548baeae6956df346ec8c17f5ea10f35ee3cbc514797ed7ddd3145464e2a0bab413",
                            personid = 1,
                            roleid = 1,
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 531, DateTimeKind.Local).AddTicks(4454),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 2,
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 531, DateTimeKind.Local).AddTicks(4528),
                            createdby = "Seed Data",
                            email = "user2@mail.com",
                            password = "ba3253876aed6bc22d4a6ff53d8406c6ad864195ed144ab5c87621b6c233b548baeae6956df346ec8c17f5ea10f35ee3cbc514797ed7ddd3145464e2a0bab413",
                            personid = 2,
                            roleid = 2,
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 531, DateTimeKind.Local).AddTicks(4530),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 3,
                            createdate = new DateTime(2022, 1, 28, 14, 41, 3, 531, DateTimeKind.Local).AddTicks(4566),
                            createdby = "Seed Data",
                            email = "user3@mail.com",
                            password = "ba3253876aed6bc22d4a6ff53d8406c6ad864195ed144ab5c87621b6c233b548baeae6956df346ec8c17f5ea10f35ee3cbc514797ed7ddd3145464e2a0bab413",
                            personid = 3,
                            roleid = 3,
                            updatedate = new DateTime(2022, 1, 28, 14, 41, 3, 531, DateTimeKind.Local).AddTicks(4569),
                            updatedby = "Seed Data"
                        });
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Course", b =>
                {
                    b.HasOne("SchoolApp.Infrastructure.Models.Classes.Professor", "professor")
                        .WithMany("courses")
                        .HasForeignKey("professorid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SchoolApp.Infrastructure.Models.Classes.Student", "student")
                        .WithMany("courses")
                        .HasForeignKey("studentid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("professor");

                    b.Navigation("student");
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Professor", b =>
                {
                    b.HasOne("SchoolApp.Infrastructure.Models.Classes.Person", "person")
                        .WithMany("professors")
                        .HasForeignKey("personid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("person");
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Student", b =>
                {
                    b.HasOne("SchoolApp.Infrastructure.Models.Classes.Level", "level")
                        .WithMany("students")
                        .HasForeignKey("levelid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolApp.Infrastructure.Models.Classes.Person", "person")
                        .WithMany("students")
                        .HasForeignKey("personid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("level");

                    b.Navigation("person");
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.User", b =>
                {
                    b.HasOne("SchoolApp.Infrastructure.Models.Classes.Person", "person")
                        .WithMany("users")
                        .HasForeignKey("personid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolApp.Infrastructure.Models.Classes.Role", "role")
                        .WithMany("users")
                        .HasForeignKey("roleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("person");

                    b.Navigation("role");
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Level", b =>
                {
                    b.Navigation("students");
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Person", b =>
                {
                    b.Navigation("professors");

                    b.Navigation("students");

                    b.Navigation("users");
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Professor", b =>
                {
                    b.Navigation("courses");
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Role", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Student", b =>
                {
                    b.Navigation("courses");
                });
#pragma warning restore 612, 618
        }
    }
}
