// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolApp.Infrastructure.DatabaseContext;

#nullable disable

namespace SchoolApp.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContextSchool))]
    partial class DatabaseContextSchoolModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Course", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("coursename")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("createdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("createdby")
                        .HasColumnType("TEXT");

                    b.Property<int>("professorid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("studentid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("TEXT");

                    b.Property<string>("updatedby")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("professorid");

                    b.HasIndex("studentid");

                    b.ToTable("courses");

                    b.HasData(
                        new
                        {
                            id = 1,
                            coursename = "Course 1",
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 197, DateTimeKind.Local).AddTicks(529),
                            createdby = "Seed Data",
                            professorid = 1,
                            studentid = 1,
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 197, DateTimeKind.Local).AddTicks(540),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 2,
                            coursename = "Course 2",
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 197, DateTimeKind.Local).AddTicks(579),
                            createdby = "Seed Data",
                            professorid = 2,
                            studentid = 2,
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 197, DateTimeKind.Local).AddTicks(581),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 3,
                            coursename = "Course 3",
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 197, DateTimeKind.Local).AddTicks(584),
                            createdby = "Seed Data",
                            professorid = 3,
                            studentid = 3,
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 197, DateTimeKind.Local).AddTicks(586),
                            updatedby = "Seed Data"
                        });
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Level", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("createdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("createdby")
                        .HasColumnType("TEXT");

                    b.Property<string>("levelname")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("TEXT");

                    b.Property<string>("updatedby")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("levels");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4118),
                            createdby = "Seed Data",
                            levelname = "Level 1",
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4306),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 2,
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4320),
                            createdby = "Seed Data",
                            levelname = "Level 2",
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4322),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 3,
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4324),
                            createdby = "Seed Data",
                            levelname = "Level 3",
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4326),
                            updatedby = "Seed Data"
                        });
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("birthdate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("createdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("createdby")
                        .HasColumnType("TEXT");

                    b.Property<string>("firstname")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastname")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("TEXT");

                    b.Property<string>("updatedby")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("persons");

                    b.HasData(
                        new
                        {
                            id = 1,
                            birthdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4711),
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4715),
                            createdby = "Seed Data",
                            firstname = "Marouane",
                            lastname = "EL MABROUK",
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4717),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 2,
                            birthdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4723),
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4724),
                            createdby = "Seed Data",
                            firstname = "Smith",
                            lastname = "JOHN",
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4726),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 3,
                            birthdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4729),
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4730),
                            createdby = "Seed Data",
                            firstname = "William",
                            lastname = "MILLER",
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4736),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 4,
                            birthdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4739),
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4740),
                            createdby = "Seed Data",
                            firstname = "Prof",
                            lastname = "EL MABROUK",
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4742),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 5,
                            birthdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4744),
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4746),
                            createdby = "Seed Data",
                            firstname = "Prof",
                            lastname = "JOHN",
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4748),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 6,
                            birthdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4752),
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4753),
                            createdby = "Seed Data",
                            firstname = "Prof",
                            lastname = "MILLER",
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(4755),
                            updatedby = "Seed Data"
                        });
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Professor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("createdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("createdby")
                        .HasColumnType("TEXT");

                    b.Property<int>("personid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("photoprofessor")
                        .HasColumnType("TEXT");

                    b.Property<string>("profcode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("TEXT");

                    b.Property<string>("updatedby")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("personid");

                    b.ToTable("professors");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(6366),
                            createdby = "Seed Data",
                            personid = 4,
                            photoprofessor = "avatar.png",
                            profcode = "CODE_1",
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(6378),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 2,
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(6385),
                            createdby = "Seed Data",
                            personid = 5,
                            photoprofessor = "avatar.png",
                            profcode = "CODE_2",
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(6387),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 3,
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(6389),
                            createdby = "Seed Data",
                            personid = 6,
                            photoprofessor = "avatar.png",
                            profcode = "CODE_3",
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(6391),
                            updatedby = "Seed Data"
                        });
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("createdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("createdby")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<int>("role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("TEXT");

                    b.Property<string>("updatedby")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(6675),
                            createdby = "Seed Data",
                            description = "Super Administrator Description",
                            role = 1,
                            title = "Super Administrator",
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(6679),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 2,
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(6683),
                            createdby = "Seed Data",
                            description = "Administrator Description",
                            role = 2,
                            title = "Administrator",
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(6685),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 3,
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(6688),
                            createdby = "Seed Data",
                            description = "Professor Description",
                            role = 3,
                            title = "Professor",
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(6689),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 4,
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(6692),
                            createdby = "Seed Data",
                            description = "Student Description",
                            role = 4,
                            title = "User",
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(6694),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 5,
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(6696),
                            createdby = "Seed Data",
                            description = "User Description",
                            role = 5,
                            title = "User",
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(6698),
                            updatedby = "Seed Data"
                        });
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("createdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("createdby")
                        .HasColumnType("TEXT");

                    b.Property<int>("levelid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("personid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("photostudent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("TEXT");

                    b.Property<string>("updatedby")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("levelid");

                    b.HasIndex("personid");

                    b.ToTable("students");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(8613),
                            createdby = "Seed Data",
                            levelid = 1,
                            personid = 1,
                            photostudent = "avatar.png",
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(8624),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 2,
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(8629),
                            createdby = "Seed Data",
                            levelid = 2,
                            personid = 2,
                            photostudent = "avatar.png",
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(8631),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 3,
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(8633),
                            createdby = "Seed Data",
                            levelid = 3,
                            personid = 3,
                            photostudent = "avatar.png",
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 196, DateTimeKind.Local).AddTicks(8635),
                            updatedby = "Seed Data"
                        });
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("createdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("createdby")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isOnline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<int>("personid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("roleid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("TEXT");

                    b.Property<string>("updatedby")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("personid");

                    b.HasIndex("roleid");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 197, DateTimeKind.Local).AddTicks(2675),
                            createdby = "Seed Data",
                            email = "user1@mail.com",
                            isOnline = false,
                            password = "ba3253876aed6bc22d4a6ff53d8406c6ad864195ed144ab5c87621b6c233b548baeae6956df346ec8c17f5ea10f35ee3cbc514797ed7ddd3145464e2a0bab413",
                            personid = 1,
                            roleid = 1,
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 197, DateTimeKind.Local).AddTicks(2686),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 2,
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 197, DateTimeKind.Local).AddTicks(2766),
                            createdby = "Seed Data",
                            email = "user2@mail.com",
                            isOnline = false,
                            password = "ba3253876aed6bc22d4a6ff53d8406c6ad864195ed144ab5c87621b6c233b548baeae6956df346ec8c17f5ea10f35ee3cbc514797ed7ddd3145464e2a0bab413",
                            personid = 2,
                            roleid = 2,
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 197, DateTimeKind.Local).AddTicks(2769),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 3,
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 197, DateTimeKind.Local).AddTicks(2807),
                            createdby = "Seed Data",
                            email = "user3@mail.com",
                            isOnline = false,
                            password = "ba3253876aed6bc22d4a6ff53d8406c6ad864195ed144ab5c87621b6c233b548baeae6956df346ec8c17f5ea10f35ee3cbc514797ed7ddd3145464e2a0bab413",
                            personid = 3,
                            roleid = 3,
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 197, DateTimeKind.Local).AddTicks(2809),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 4,
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 197, DateTimeKind.Local).AddTicks(2871),
                            createdby = "Seed Data",
                            email = "user4@mail.com",
                            isOnline = false,
                            password = "ba3253876aed6bc22d4a6ff53d8406c6ad864195ed144ab5c87621b6c233b548baeae6956df346ec8c17f5ea10f35ee3cbc514797ed7ddd3145464e2a0bab413",
                            personid = 4,
                            roleid = 4,
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 197, DateTimeKind.Local).AddTicks(2873),
                            updatedby = "Seed Data"
                        },
                        new
                        {
                            id = 5,
                            createdate = new DateTime(2022, 2, 5, 22, 14, 6, 197, DateTimeKind.Local).AddTicks(2910),
                            createdby = "Seed Data",
                            email = "user5@mail.com",
                            isOnline = false,
                            password = "ba3253876aed6bc22d4a6ff53d8406c6ad864195ed144ab5c87621b6c233b548baeae6956df346ec8c17f5ea10f35ee3cbc514797ed7ddd3145464e2a0bab413",
                            personid = 5,
                            roleid = 5,
                            updatedate = new DateTime(2022, 2, 5, 22, 14, 6, 197, DateTimeKind.Local).AddTicks(2912),
                            updatedby = "Seed Data"
                        });
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Course", b =>
                {
                    b.HasOne("SchoolApp.Infrastructure.Models.Classes.Professor", "professor")
                        .WithMany("courses")
                        .HasForeignKey("professorid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SchoolApp.Infrastructure.Models.Classes.Student", "student")
                        .WithMany("courses")
                        .HasForeignKey("studentid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("professor");

                    b.Navigation("student");
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Professor", b =>
                {
                    b.HasOne("SchoolApp.Infrastructure.Models.Classes.Person", "person")
                        .WithMany("professors")
                        .HasForeignKey("personid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("person");
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Student", b =>
                {
                    b.HasOne("SchoolApp.Infrastructure.Models.Classes.Level", "level")
                        .WithMany("students")
                        .HasForeignKey("levelid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolApp.Infrastructure.Models.Classes.Person", "person")
                        .WithMany("students")
                        .HasForeignKey("personid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("level");

                    b.Navigation("person");
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.User", b =>
                {
                    b.HasOne("SchoolApp.Infrastructure.Models.Classes.Person", "person")
                        .WithMany("users")
                        .HasForeignKey("personid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolApp.Infrastructure.Models.Classes.Role", "role")
                        .WithMany("users")
                        .HasForeignKey("roleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("person");

                    b.Navigation("role");
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Level", b =>
                {
                    b.Navigation("students");
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Person", b =>
                {
                    b.Navigation("professors");

                    b.Navigation("students");

                    b.Navigation("users");
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Professor", b =>
                {
                    b.Navigation("courses");
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Role", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("SchoolApp.Infrastructure.Models.Classes.Student", b =>
                {
                    b.Navigation("courses");
                });
#pragma warning restore 612, 618
        }
    }
}
